micronaut:
    application:
        name: nfce-reading
    security:
        authentication: bearer
        token:
            jwt:
                signatures:
                    secret:
                        generator:
                            secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
        enabled: false
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
            swagger-ui:
                paths: classpath:META-INF/swagger/views/swagger-ui
                mapping: /swagger-ui/**
    server:
        port: 8080
datasources:
    default:
        url: 'jdbc:postgresql://localhost:5432/nfce-database'
        username: 'postgres'
        password: 'postgres'
        driverClassName: 'org.postgresql.Driver'
jpa:
    default:
        packages-to-scan:
            - 'github.sagubr'
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true
liquibase:
    datasources: # (2)
        default: # (3)
            change-log: 'classpath:db/liquibase-changelog.xml' # (4)